# This rule is not used by the project aare-guru itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants read-only access to stats.aare.guru resources.
# This role is intended for users who need visibility into these resources
# without permissions to modify them. It is ideal for monitoring purposes and limited-access viewing.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: aare-guru
    app.kubernetes.io/managed-by: kustomize
  name: currenttemperature-viewer-role
rules:
- apiGroups:
  - stats.aare.guru
  resources:
  - currenttemperatures
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - stats.aare.guru
  resources:
  - currenttemperatures/status
  verbs:
  - get
