---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - stats.aare.guru
  resources:
  - currenttemperatures
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - stats.aare.guru
  resources:
  - currenttemperatures/finalizers
  verbs:
  - update
- apiGroups:
  - stats.aare.guru
  resources:
  - currenttemperatures/status
  verbs:
  - get
  - patch
  - update
