//go:build !ignore_autogenerated

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CurrentTemperature) DeepCopyInto(out *CurrentTemperature) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CurrentTemperature.
func (in *CurrentTemperature) DeepCopy() *CurrentTemperature {
	if in == nil {
		return nil
	}
	out := new(CurrentTemperature)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *CurrentTemperature) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CurrentTemperatureList) DeepCopyInto(out *CurrentTemperatureList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]CurrentTemperature, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CurrentTemperatureList.
func (in *CurrentTemperatureList) DeepCopy() *CurrentTemperatureList {
	if in == nil {
		return nil
	}
	out := new(CurrentTemperatureList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *CurrentTemperatureList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CurrentTemperatureSpec) DeepCopyInto(out *CurrentTemperatureSpec) {
	*out = *in
	out.UpdateInterval = in.UpdateInterval
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CurrentTemperatureSpec.
func (in *CurrentTemperatureSpec) DeepCopy() *CurrentTemperatureSpec {
	if in == nil {
		return nil
	}
	out := new(CurrentTemperatureSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CurrentTemperatureStatus) DeepCopyInto(out *CurrentTemperatureStatus) {
	*out = *in
	in.Updated.DeepCopyInto(&out.Updated)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CurrentTemperatureStatus.
func (in *CurrentTemperatureStatus) DeepCopy() *CurrentTemperatureStatus {
	if in == nil {
		return nil
	}
	out := new(CurrentTemperatureStatus)
	in.DeepCopyInto(out)
	return out
}
